{
    "openapi": "3.0.0",
    "info": {
        "title": "201 Project API",
        "version": "1.0"
    },
    "paths": {
        "/api/groups/list": {
            "get": {
                "tags": [
                    "Groups"
                ],
                "summary": "List all the groups and their IDs",
                "responses": {
                    "200": {
                        "description": "Groups have been retrieved",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "properties": {
                                                "id": {
                                                    "type": "int"
                                                },
                                                "name": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": [
                                        {
                                            "id": 1,
                                            "name": "201"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/groups/items": {
            "get": {
                "tags": [
                    "Groups"
                ],
                "summary": "Get a group's subscibed items",
                "operationId": "App\\Http\\Controllers\\GroupController::items",
                "responses": {
                    "200": {
                        "description": "Group items have been retrieved",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "properties": {
                                                "id": {
                                                    "type": "int"
                                                },
                                                "group_id": {
                                                    "type": "int"
                                                },
                                                "name": {
                                                    "type": "string"
                                                },
                                                "pic_url": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": [
                                        {
                                            "id": 1,
                                            "group_id": 1,
                                            "name": "Banana",
                                            "in_stock": 1,
                                            "pic_url": null
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/groups/subscribe/{group_id}": {
            "post": {
                "tags": [
                    "Groups"
                ],
                "summary": "Subscribe a user to a group",
                "operationId": "App\\Http\\Controllers\\GroupController::subscribe",
                "responses": {
                    "200": {
                        "description": "User has been subscribed to group",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "User has been subscribed to group 201"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/groups/unsubscribe": {
            "post": {
                "tags": [
                    "Groups"
                ],
                "summary": "Unsubscribe a user from a group",
                "operationId": "App\\Http\\Controllers\\GroupController::unsubscribe",
                "responses": {
                    "200": {
                        "description": "User has been unsubscribed from their group",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "User has been unsubscribed to group 201"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/groups/subscribers": {
            "get": {
                "tags": [
                    "Groups"
                ],
                "summary": "Gets the list of users subscribed to users Group",
                "operationId": "App\\Http\\Controllers\\GroupController::subscribers",
                "responses": {
                    "200": {
                        "description": "Group subscribers returned",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": [
                                        {
                                            "id": 2,
                                            "group_id": null,
                                            "name": "Kristof",
                                            "pic_url": null,
                                            "email": "kristof@usc.edu",
                                            "created_at": "2018-10-30 01:13:02"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/groups/create": {
            "post": {
                "tags": [
                    "Groups"
                ],
                "summary": "Create a new group and subscribe to it",
                "operationId": "App\\Http\\Controllers\\GroupController::create",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Group created and user subscribed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "id": "1",
                                        "name": "201"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/items/create": {
            "post": {
                "tags": [
                    "Items"
                ],
                "summary": "Create a new item and subscribe to it",
                "operationId": "App\\Http\\Controllers\\ItemController::create",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Item created and user subscribed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "id": "1",
                                        "group_id": "1",
                                        "name": "Banana",
                                        "in_stock": "1"
                                    }
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Item created and user subscribed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "Item already exists"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/items/subscribers/{item_id}": {
            "get": {
                "tags": [
                    "Items"
                ],
                "summary": "Gets the list of users subscribed to a Item",
                "operationId": "App\\Http\\Controllers\\ItemController::subscribers",
                "responses": {
                    "200": {
                        "description": "Item subscribers returned",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": [
                                        {
                                            "id": 2,
                                            "group_id": null,
                                            "name": "Kristof",
                                            "pic_url": null,
                                            "email": "kristof@usc.edu",
                                            "created_at": "2018-10-30 01:13:02"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/items/subscribe/{item_id}": {
            "post": {
                "tags": [
                    "Items"
                ],
                "summary": "Subscribe a user to an Item",
                "operationId": "App\\Http\\Controllers\\ItemController::subscribe",
                "responses": {
                    "200": {
                        "description": "User subscribed to Item",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "id": "1",
                                        "group_id": "1",
                                        "name": "Banana",
                                        "in_stock": "1"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/items/unsubscribe/{item_id}": {
            "post": {
                "tags": [
                    "Items"
                ],
                "summary": "Unsubscribe a user to an Item",
                "operationId": "App\\Http\\Controllers\\ItemController::unsubscribe",
                "responses": {
                    "200": {
                        "description": "User unsubscribed to Item",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "id": "1",
                                        "group_id": "1",
                                        "name": "Banana",
                                        "in_stock": "1"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/items/in-stock/{item_id}": {
            "post": {
                "tags": [
                    "Items"
                ],
                "summary": "Mark a item as in stock",
                "operationId": "App\\Http\\Controllers\\ItemController::inStock",
                "responses": {
                    "200": {
                        "description": "Item indicated as in stock",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "Item marked in stock"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "Item not found"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/items/out-of-stock/{item_id}": {
            "post": {
                "tags": [
                    "Items"
                ],
                "summary": "Mark a item as out of stock",
                "operationId": "App\\Http\\Controllers\\ItemController::outOfStock",
                "responses": {
                    "200": {
                        "description": "Item indicated as out of stock",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "Item marked out of stock"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "Item not found"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/transactions/purchase": {
            "post": {
                "tags": [
                    "Transactions"
                ],
                "summary": "Purchase an item and notify group",
                "operationId": "App\\Http\\Controllers\\TransactionController::purchase",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "properties": {
                                    "item_id": {
                                        "type": "int"
                                    },
                                    "price": {
                                        "type": "numeric"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Item purchased successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "user_id": 1,
                                        "group_id": 1,
                                        "item_id": 1,
                                        "price": "5.99",
                                        "created_at": "2018-11-24 06:30:54",
                                        "id": 27
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/login": {
            "post": {
                "tags": [
                    "Login, Logout, and Registration"
                ],
                "summary": "Login a user",
                "operationId": "App\\Http\\Controllers\\UserController::login",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "email"
                                    },
                                    "password": {
                                        "type": "password"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "token": "1KJGK234..."
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                }
            }
        },
        "/api/logout": {
            "post": {
                "tags": [
                    "Login, Logout, and Registration"
                ],
                "summary": "Logout a user",
                "operationId": "App\\Http\\Controllers\\UserController::logout",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "Token has been revoked"
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/register": {
            "post": {
                "tags": [
                    "Login, Logout, and Registration"
                ],
                "summary": "Register a new user",
                "operationId": "App\\Http\\Controllers\\UserController::register",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "email"
                                    },
                                    "password": {
                                        "type": "password"
                                    },
                                    "c_password": {
                                        "type": "password"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Registration successful",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "token": "1KJGK234..."
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/400"
                    },
                    "409": {
                        "description": "User could not be created due to a conflict. User already exists.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "error": "User already exists"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/users/details": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get a users basic information",
                "operationId": "App\\Http\\Controllers\\UserController::details",
                "responses": {
                    "200": {
                        "description": "User details have been retrieved",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "properties": {
                                                "id": {
                                                    "type": "int"
                                                },
                                                "group_id": {
                                                    "type": "int"
                                                },
                                                "name": {
                                                    "type": "string"
                                                },
                                                "pic_url": {
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "type": "string"
                                                },
                                                "created_at": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": {
                                        "id": 2,
                                        "group_id": null,
                                        "name": "Kristof",
                                        "pic_url": null,
                                        "email": "kristof@usc.edu",
                                        "created_at": "2018-10-30 01:13:02"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        },
        "/api/users/items": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get a user's subscibed items",
                "operationId": "App\\Http\\Controllers\\UserController::items",
                "responses": {
                    "200": {
                        "description": "User items have been retrieved",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "properties": {
                                                "id": {
                                                    "type": "int"
                                                },
                                                "group_id": {
                                                    "type": "int"
                                                },
                                                "name": {
                                                    "type": "string"
                                                },
                                                "pic_url": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": [
                                        {
                                            "id": 1,
                                            "group_id": 1,
                                            "name": "Banana",
                                            "in_stock": 1,
                                            "pic_url": null
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    }
                },
                "security": [
                    "bearer"
                ]
            }
        }
    },
    "components": {
        "responses": {
            "401": {
                "description": "Request is not authorized",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "example": {
                            "error": "Unauthorized"
                        }
                    }
                }
            },
            "400": {
                "description": "Bad request",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "example": {
                            "error": "Bad request"
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "bearer": {
                "type": "http",
                "bearerFormat": "JWT"
            }
        }
    }
}